jobs:
  build_and_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Гарантируем, что в облаке есть инструменты для сборки DEB и RPM
    - name: Install Packaging Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm binutils dpkg

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON

    - name: Build Project
      run: cmake --build _build

    - name: Run Tests
      run: cmake --build _build --target test

    # Собираем пакеты по отдельности, чтобы точно видеть, если какой-то упадет
    - name: Generate Packages via CPack
      run: |
        cd _build
        cpack -G TGZ
        cpack -G DEB
        cpack -G RPM

    # Выводим список файлов в консоль экшена (для дебага, если что-то пойдет не так)
    - name: List Generated Packages
      run: find _build/ -maxdepth 2 -name "*.deb" -o -name "*.rpm" -o -name "*.tar.gz"

    # Используем двойную звездочку , чтобы экшен нашел файлы в ЛЮБЫХ подпапках _build
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          _build//*.tar.gz
          _build//*.deb
          _build//*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
