name: CMake Packaging

on: [push, pull_request]

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON -DCPACK_GENERATOR="TGZ"

    - name: Build Project
      run: cmake --build _build

    - name: Run Tests
      run: cmake --build _build --target test

    - name: Generate Package via CPack
      run: |
        cd _build
        cpack -G "TGZ"

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: print-package
        path: _build/*.tar.gz
